# values that various classes use to determine their behavior

ENCODER_DIR_CHANGE_MARGIN = 2
RADIO_MAX_TRIES = 50
RADIO_STATION = 101.9
CLOCK_START_DATETIME = (2023, 1, 1, 1, 1, 1, 1, 0)
DISPLAY_SCREEN_HEIGHT = 64
DISPLAY_SCREEN_WIDTH = 128
BUTTON_DOWNTIME_MS = 20
BUTTON_HOLDTIME_MS = 800
UPDATE_FREQ = 15
VOL_MULTIPLIER = 0.25
FREQ_MULTIPLIER = 0.2
TIME_MULTIPLIER = 1
MODE_TIMEOUT = 30
SNOOZE_DELAY = 6
INFO_TIMEOUT = 0.8
FLASH_LENGTH = 1
FLASH_DS = 0.6
