# values that various classes use to determine their behaviour

ENCODER_DIR_CHANGE_MARGIN = 1
RADIO_MAX_TRIES = 10
RADIO_STATION = 101.9
CLOCK_START_DATETIME = (2023, 1, 1, 1, 1, 1, 1, 1)
DISPLAY_SCREEN_HEIGHT = 64
DISPLAY_SCREEN_WIDTH = 128
BUTTON_DOWNTIME_MS = 20
BUTTON_HOLDTIME_MS = 800
